import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from '@/libs/redux/providers'
import { RouteGuard } from '@/components/route-guard'
import Header from '@/components/header'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full w-full">
      <body className={inter.className}>
        <Providers>
            <main className="h-screen flex flex-col">
              <RouteGuard>
                <Header/>
                {children}
                <Footer/>
              </RouteGuard>
            </main>
        </Providers>
      </body>
    </html>
  )
}
